# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: sspsign

on:
  watch:
    types: [ started ]
  schedule:
    - cron: 0 16 * * *
jobs:
  build:
    if: ${{ github.actor == github.event.repository.owner.login || github.event_name == 'schedule' }}
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: init
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run
      env:
        ssp: ${{ secrets.hostloc }} 
        fs: ${{ secrets.fs }} 
        ssp_telkey: ${{ secrets.hostloc_telkey }} 
        ssp_skey: ${{ secrets.hostloc_skey }}
        ssp_qkey: ${{ secrets.hostloc_qkey }}
        ssp_push: ${{ secrets.hostloc_push }}
        ssp_ktkey: ${{ secrets.hostloc_ktkey }}
      run: |
        python3 hostloc.py
